version: 1

formatters:
    simple:
        format: "%(asctime)s [%(levelname)s] %(processName)s [%(threadName)s] %(name)s: %(message)s "


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

loggers:
    main:
        level: INFO
        handlers: [console]
        propagate: yes